[build]
  publish = "public"
  command = "echo 'No build command needed'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  VITE_SUPABASE_URL = "Your Supabase URL"
  VITE_SUPABASE_KEY = "Your Supabase Anon Key"
